#List of items that are not allowed to be put in backpacks - e.g. "minecraft:shulker_box"
disallowedItems = []
#Determines if container items (those that override canFitInsideContainerItems to false) are able to fit in backpacks
containerItemsDisallowed = false
#List of blocks that inventory interaction upgrades can't interact with - e.g. "minecraft:shulker_box"
noInteractionBlocks = []
#List of blocks that are not allowed to connect to backpacks - e.g. "refinedstorage:external_storage"
noConnectionBlocks = []
#If true, disallows all blocks from connecting to backpacks
allBlockConnectionsDisallowed = false
#Maximum number of upgrades of type per backpack in format of "UpgradeRegistryName[or UpgradeGroup]|MaxNumber"
maxUpgradesPerStorage = ["stack_upgrades|3", "furnace_upgrades|1", "jukebox_upgrades|1"]
#Turns on/off item fluid handler of backpack in its item form. There are some dupe bugs caused by default fluid handling implementation that manifest when backpack is drained / filled in its item form in another mod's tank and the only way to prevent them is disallowing drain/fill in item form altogether
itemFluidHandlerEnabled = true
#Determines whether player can right click on backpack that another player is wearing to open it. If off will turn off that capability for everyone and remove related settings from backpack.
allowOpeningOtherPlayerBackpacks = true
#Allows disabling item display settings. Primarily in cases where custom backpack model doesn't support showing the item. (Requires game restart to take effect)
itemDisplayDisabled = false
#Allows disabling logic that dedupes backpacks with the same UUID in players' inventory. This is here to allow turning off the logic just in case it would be causing performance issues.
tickDedupeLogicDisabled = false
#Determines if backpacks can be placed in container items (those that check for return value of canFitInsideContainerItems)
canBePlacedInContainerItems = false